# Generated by Django 5.2.4 on 2025-08-07 22:08

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('product_desc', models.CharField(default='', max_length=1000)),
                ('product_pub_date', models.DateField(default=datetime.date.today)),
                ('product_end_date', models.DateField(default=accounts.models.ten_days_later)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
                ('product_start_price', models.IntegerField(default=0)),
                ('product_end_price', models.IntegerField(default=0)),
                ('product_mid_price', models.IntegerField(default=0)),
                ('product_owner', models.IntegerField(default=0)),
                ('product_winner', models.IntegerField(default=None)),
                ('product_bidders', models.CharField(default='', max_length=200)),
                ('product_status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
