# Generated by Django 5.2.4 on 2025-08-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='', upload_to='auctions/images'),
        ),
    ]
