# Generated by Django 5.2.4 on 2025-08-10 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_products_product_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
