# Generated by Django 5.2.4 on 2025-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='seller_id',
            field=models.IntegerField(default=0),
        ),
    ]
