# Generated by Django 5.2.4 on 2025-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_messages_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_head',
            field=models.CharField(default='', max_length=100),
        ),
    ]
