# Generated by Django 5.2.4 on 2025-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_messages_message_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_winner',
            field=models.IntegerField(default=-1),
        ),
    ]
