# Generated by Django 5.2.4 on 2025-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_products_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_winner',
            field=models.CharField(default=-1),
        ),
    ]
