# Generated by Django 5.2.4 on 2025-08-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_products_product_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_bids_count',
            field=models.IntegerField(default=0),
        ),
    ]
