# Generated by Django 5.2.4 on 2025-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_products_product_bids_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_winner_id',
            field=models.IntegerField(default=-1),
        ),
    ]
